name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: echo "Temporarily skipping npm install to test workflow"
      - run: echo "npm run lint would run here"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: echo "Temporarily skipping npm install to test workflow"
      - run: echo "npm test would run here"

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: echo "Temporarily skipping npm install to test workflow"
      - run: echo "npm run test:e2e would run here"

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: echo "Temporarily skipping npm install to test workflow"
      - run: echo "npm run build would run here"
      - run: mkdir -p build && echo "test" > build/test.txt
      - uses: actions/upload-artifact@v4
        with:
          name: extension-build
          path: build/